.catalog:
    name: WordpressCICP2R
    version: v0.0.2-rancher2
    description: Wordpress Public site of CICP2R
    category: Rancher Services
    questions:
    - variable: "VOLUME_NAME"
      description: "Name to give the Gluster volume"
      label: "Volume Name"
      required: true
      default: "phpsessionsync"
      type: "string"

lb-cicp2r:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
glusterfs-server:
  scale: 3
  metadata:
    volume_name: "${VOLUME_NAME}"