name: Registry-djz
description: |
  Secure Docker registry.  Web based administration.  Optional LDAP authentication.
version: v2.3.1-3.1-djoulz221
category: Applications
maintainer: Steve Shipway <s.shipway@auckland.ac.nz>

