.catalog:
    name: WordpressCICP2R
    version: v0.0.1-rancher1
    description: Wordpress Public site of CICP2R

lb-cicp2r:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
