.catalog:
  name: "MongoDB-djz"
  version: "3.0.0-djoulz221"
  description: "MongoDB Replica Set"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
mongo-cluster:
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
